export const LOCATION_TO_BUILDING: Record<string, string> = {
  'Idrettshall':        'idrettshall',
  'Svømmehall':         'svommehall',
  'Basseng':            'svommehall',
  'Svømming':           'svommehall',
  'Gymsal':             'gymsal',
  'Gymsal/gard./trim':  'gymsal',
  'Trim':               'gymsal',
  'Ridehall':           'ridehall',
  'Ridning':            'ridehall',
  'Stall':              'stall',
  'Stall/adm':          'stall',
  'Skole':              'skole',
  'Spisesal':           'spisesal',
  'Familiehus':         'familiehus',
  'Lege':               'lege',
  'Hjelpemiddelbygg':   'hjelpemiddelbygg',
  'Hovedbygg':          'hovedbygg',
  'Paviljongen':        'paviljongen',
};
